# Generated by Django 5.2.14 on 2026-05-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_payload', models.TextField(default='{}')),
                ('status', models.CharField(default='ALLOWED', max_length=50)),
                ('failure_reason', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
