# Generated by Django 6.0.5 on 2026-05-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CloudApiLog',
        ),
    ]
